test
dequis/test pull request #3
Opened 2016-09-11 20:40 UTC by cblgh

2016-09-11 20:56 UTC, dequis commented
Thanks for your pull request.  It looks like this may be your first contribution to a dequis open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: **Please visit <https://cla.developers.dequis.org/> to sign.**

Once you've signed, please reply here (e.g. `I signed it!`) and we'll verify.  Thanks.

---

- If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check [your existing CLA data](https://cla.developers.dequis.org/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
- If you signed the CLA as a corporation, please let us know the company's name.

<!-- need_sender_cla -->

2016-09-11 20:59 UTC, dequis commented
## [Current coverage][cc-pull] is **92.29%**
> Merging [#3][cc-pull] into [master][cc-base-branch] will not change coverage

```diff
@@             master        #97   diff @@
==========================================
  Files            48         48
  Lines          2671       2671
  Methods           0          0
  Messages          0          0
  Branches          0          0
==========================================
  Hits           2465       2465
  Misses          206        206
  Partials          0          0
```



> Powered by [Codecov](https://codecov.io?src=pr). Last updated by [3e41c7c...3fec94d][cc-compare]
[cc-base-branch]: https://codecov.io/
[cc-compare]: https://codecov.io/
[cc-pull]: https://codecov.io/

2016-09-11 21:01 UTC, dequis commented on README.md
> +:cop: `move along nothing to see here`
E501 line too long (110 > 79 characters)

2016-09-11 21:02 UTC, cblgh commented
i....... i think i signed it. i dont get the thing about having to send you a package with a hair sample but i complied anyway, also added a cupcake recipe

2016-09-11 21:02 UTC, dequis commented on README.md
>  # test
F401 'test' imported but unused

2016-09-11 21:04 UTC, dequis commented on README.md
> -move along nothing to see here
E303 too many blank lines (4)

2016-09-11 21:08 UTC, dequis commented
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

2016-09-12 06:42 UTC, dequis commented
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

2016-09-12 06:48 UTC, dequis commented on README.md
>  # test
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

2016-09-12 07:00 UTC, dequis commented
If GitHub tells you that your branches cannot automatically be merged, you probably have merge conflicts. These should be fixed before you submit your pull request.

![GitHubPullRequestPreCreateMergeConflict.png](https://raw.githubusercontent.com/PowerShell/DscResources/master/Images/GitHubPullRequestPreCreateMergeConflict.png)

For help fixing merge conflicts see our [guide to getting started with GitHub](http://google.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bount [...]

2016-09-14 19:12 UTC, dequis commented on README.md
>  # test
F401 'test' imported but unused

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

2016-09-14 19:12 UTC, dequis commented on README.md
> -move along nothing to see here
E303 too many blank lines (4)

2016-09-14 19:12 UTC, dequis commented on README.md
> +:cop: `move along nothing to see here`
E501 line too long (110 > 79 characters)

2016-09-14 19:13 UTC, dequis requested changes
---

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/)** We accept bounties via [Bountysource](https://www.bountysource.com/).

2016-09-14 19:27 UTC, cblgh commented
DISREGARD PREVIOUS STATEMENTS


THIS IS A COUP

2016-09-14 19:27 UTC, merged

2016-09-14 19:28 UTC, dequis commented
HOW DARE YOU

DOWNVOTED YOUR COMMENT, ENJOY YOUR NEGATIVE KARMA